import argparse
import json
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from app.schemas.market_regime_schema import MarketRegimeCandle
from app.services.market_regime_dataset import (
    MARKET_REGIME_LABELS,
    build_dataset_readiness,
    build_labeled_windows,
    load_market_regime_candles,
    three_way_split,
)
from app.services.market_regime_experiment import MARKET_REGIME_FEATURE_VERSION, build_experiment_manifest, describe_path
from app.services.market_regime_experiment import (
    append_or_merge_run,
    chronological_split_index,
    generate_run_id,
    load_experiment_registry,
    write_experiment_registry,
)
from app.services.market_regime_torch_features import TORCH_MARKET_REGIME_FEATURE_ORDER
from app.services.market_regime_torch_model import (
    DEFAULT_TORCH_MODEL_CONFIG,
    TORCH_MODEL_ARCHITECTURE_V1,
    TORCH_MODEL_ARCHITECTURE_V2,
    build_attention_transformer_model,
    build_transformer_model,
)


LABELS = MARKET_REGIME_LABELS


def main() -> None:
    args = parse_args()
    torch = load_torch()
    seed_everything(torch, args.seed)
    run_id = generate_run_id()
    candles = load_candles(args.csv_path)
    windows, labels = build_training_windows(candles, args.sequence_length)
    if not windows:
        raise SystemExit("not enough candles to build training windows")
    readiness = build_dataset_readiness(candles, args.sequence_length)
    if not readiness["ready"] and not args.allow_unready_dataset:
        raise SystemExit("dataset readiness failed: " + "; ".join(readiness["failures"]))
    # Labels are generated by the rules classifier, so the model learns a weak-label baseline rather
    # than independent trading truth. Evaluation should be read as consistency and lift, not oracle accuracy.
    train_windows, validation_windows, test_windows = three_way_split(windows, args.validation_ratio, args.test_ratio)
    train_labels, validation_labels, test_labels = three_way_split(labels, args.validation_ratio, args.test_ratio)

    # Fit normalization on training windows only, then reuse those stats for validation and inference.
    # This avoids leaking later validation-window statistics into training-time preprocessing.
    means, stds = normalization_stats(train_windows)
    normalized_train_windows = [
        normalize_window(window, means, stds)
        for window in train_windows
    ]
    normalized_validation_windows = [
        normalize_window(window, means, stds)
        for window in validation_windows
    ]
    device = torch.device("cuda" if torch.cuda.is_available() and not args.cpu else "cpu")
    model_config = build_model_config(args)

    inputs = torch.tensor(normalized_train_windows, dtype=torch.float32, device=device)
    targets = torch.tensor(train_labels, dtype=torch.long, device=device)
    model = build_training_model(torch, args.architecture, model_config).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.learning_rate)
    class_weights = balanced_class_weights(train_labels, len(LABELS)) if args.class_weighting == "balanced" else None
    weight_tensor = torch.tensor(class_weights, dtype=torch.float32, device=device) if class_weights is not None else None
    loss_function = torch.nn.CrossEntropyLoss(weight=weight_tensor)

    training_outcome = train_with_early_stopping(
        torch,
        model,
        optimizer,
        loss_function,
        inputs,
        targets,
        normalized_validation_windows,
        validation_labels,
        epochs=args.epochs,
        batch_size=args.batch_size,
        patience=args.patience,
        seed=args.seed,
        device=device,
        selection_metric=args.selection_metric,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "metadata": {
                "runId": run_id,
                "modelVersion": args.model_version,
                "featureVersion": MARKET_REGIME_FEATURE_VERSION,
                "sequenceLength": args.sequence_length,
                "featureOrder": TORCH_MARKET_REGIME_FEATURE_ORDER,
                "labels": LABELS,
                "architecture": args.architecture,
                "normalization": {"mean": means, "std": stds},
                "model": model_config,
                "evaluationHoldout": evaluation_holdout_metadata(
                    args,
                    candles,
                    len(train_windows),
                    len(validation_windows),
                    len(test_windows),
                ),
            },
            "modelStateDict": model.cpu().state_dict(),
        },
        args.output,
    )
    manifest_path, manifest = write_experiment_manifest(
        args,
        candles,
        windows,
        train_windows,
        validation_windows,
        train_labels,
        validation_labels,
        test_labels,
        len(test_windows),
        model_config,
        training_outcome,
        reproducibility_block(args.seed, getattr(torch, "__version__", None)),
        str(device),
    )
    if args.experiment_name:
        register_training_experiment(args, manifest_path, manifest, run_id)


def seed_everything(torch, seed: int) -> None:
    import random

    # Seed Python and torch so repeated local runs are comparable when config is unchanged.
    random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def build_model_config(args: argparse.Namespace) -> dict:
    config = dict(DEFAULT_TORCH_MODEL_CONFIG)
    if args.dropout is not None:
        config["dropout"] = args.dropout
    if args.no_positional_encoding:
        config["usePositionalEncoding"] = False
    return config


def build_training_model(torch, architecture: str, model_config: dict):
    """Select the artifact architecture while keeping v1 as the stable default."""
    builder = (
        build_attention_transformer_model
        if architecture == TORCH_MODEL_ARCHITECTURE_V2
        else build_transformer_model
    )
    return builder(
        torch,
        feature_count=len(TORCH_MARKET_REGIME_FEATURE_ORDER),
        class_count=len(LABELS),
        config=model_config,
    )


def build_minibatches(item_count: int, batch_size: int, seed: int) -> list[list[int]]:
    """Return a deterministic shuffled set of index batches for one epoch."""
    import random

    indices = list(range(item_count))
    random.Random(seed).shuffle(indices)
    return [indices[start : start + batch_size] for start in range(0, item_count, batch_size)]


def select_best_epoch(history: list[dict[str, float]], metric: str = "valAccuracy") -> int:
    """Return the 1 based epoch with the highest requested validation metric.

    Ties keep the earliest epoch so we favour the simpler, earlier model.
    """
    best_index = 0
    for index in range(1, len(history)):
        if history[index][metric] > history[best_index][metric]:
            best_index = index
    return best_index + 1


def train_with_early_stopping(
    torch,
    model,
    optimizer,
    loss_function,
    inputs,
    targets,
    normalized_validation_windows: list[list[list[float]]],
    validation_labels: list[int],
    *,
    epochs: int,
    batch_size: int,
    patience: int,
    seed: int,
    device,
    selection_metric: str = "accuracy",
) -> dict:
    item_count = int(inputs.shape[0])
    history: list[dict[str, float]] = []
    best_validation_score = -1.0
    best_state = None
    best_epoch = 0
    epochs_without_improvement = 0
    early_stopped = False

    for epoch in range(1, epochs + 1):
        model.train()
        batch_losses: list[float] = []
        for batch_indices in build_minibatches(item_count, batch_size, seed + epoch):
            # Change the shuffle seed per epoch while keeping the whole run reproducible.
            index_tensor = torch.tensor(batch_indices, dtype=torch.long, device=device)
            batch_inputs = inputs.index_select(0, index_tensor)
            batch_targets = targets.index_select(0, index_tensor)
            optimizer.zero_grad()
            loss = loss_function(model(batch_inputs), batch_targets)
            loss.backward()
            optimizer.step()
            batch_losses.append(float(loss.item()))

        train_loss = round(sum(batch_losses) / len(batch_losses), 6) if batch_losses else 0.0
        model.eval()
        predictions = predict_validation_labels(torch, model, normalized_validation_windows, device)
        val_accuracy = validation_accuracy(predictions, validation_labels)
        val_macro_f1 = macro_f1_from_label_indexes(
            [int(prediction["labelIndex"]) for prediction in predictions],
            validation_labels,
            len(LABELS),
        )
        val_loss = validation_loss(torch, model, loss_function, normalized_validation_windows, validation_labels, device)
        history.append(
            {
                "epoch": epoch,
                "trainLoss": train_loss,
                "valLoss": val_loss,
                "valAccuracy": val_accuracy,
                "valMacroF1": val_macro_f1,
            }
        )

        validation_score = val_macro_f1 if selection_metric == "macro-f1" else val_accuracy
        if validation_score > best_validation_score:
            # Keep the best validation state, not just the final epoch.
            best_validation_score = validation_score
            best_state = {key: value.detach().clone() for key, value in model.state_dict().items()}
            best_epoch = epoch
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1
            if epochs_without_improvement >= patience:
                early_stopped = True
                break

    if best_state is not None:
        model.load_state_dict(best_state)

    best_record = history[best_epoch - 1] if history else {"trainLoss": 0.0, "valAccuracy": 0.0, "valMacroF1": 0.0}
    return {
        "epochHistory": history,
        "bestEpoch": best_epoch,
        "earlyStopped": early_stopped,
        "finalTrainLoss": best_record["trainLoss"],
        "validationAccuracy": best_record["valAccuracy"],
        "validationMacroF1": best_record["valMacroF1"],
        "selectionMetric": selection_metric,
    }


def balanced_class_weights(labels: list[int], class_count: int) -> list[float]:
    """Return inverse-frequency weights normalized across classes observed in training."""
    counts = [labels.count(index) for index in range(class_count)]
    observed_count = sum(1 for count in counts if count > 0)
    if not labels or observed_count == 0:
        return [0.0 for _ in range(class_count)]
    return [round(len(labels) / (observed_count * count), 6) if count else 0.0 for count in counts]


def macro_f1_from_label_indexes(predicted: list[int], expected: list[int], class_count: int) -> float:
    """Average F1 over expected classes so absent output classes do not dilute the score."""
    scores = []
    for label_index in range(class_count):
        support = sum(1 for value in expected if value == label_index)
        if support == 0:
            continue
        true_positive = sum(1 for actual, guess in zip(expected, predicted, strict=True) if actual == guess == label_index)
        false_positive = sum(1 for actual, guess in zip(expected, predicted, strict=True) if actual != label_index and guess == label_index)
        false_negative = support - true_positive
        precision = true_positive / (true_positive + false_positive) if true_positive + false_positive else 0.0
        recall = true_positive / (true_positive + false_negative) if true_positive + false_negative else 0.0
        scores.append(2 * precision * recall / (precision + recall) if precision + recall else 0.0)
    return round(sum(scores) / len(scores), 4) if scores else 0.0


def validation_loss(
    torch,
    model,
    loss_function,
    normalized_validation_windows: list[list[list[float]]],
    validation_labels: list[int],
    device,
) -> float:
    if not normalized_validation_windows:
        return 0.0
    with torch.no_grad():
        inputs = torch.tensor(normalized_validation_windows, dtype=torch.float32, device=device)
        targets = torch.tensor(validation_labels, dtype=torch.long, device=device)
        return round(float(loss_function(model(inputs), targets).item()), 6)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train a local market-regime torch artifact.")
    parser.add_argument("--csv-path", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--sequence-length", type=int, default=20)
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--learning-rate", type=float, default=0.001)
    parser.add_argument("--validation-ratio", type=float, default=0.2)
    parser.add_argument("--test-ratio", type=float, default=0.2)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--patience", type=int, default=10, help="Stop after this many epochs without validation improvement.")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--class-weighting", choices=["none", "balanced"], default="none")
    parser.add_argument("--selection-metric", choices=["accuracy", "macro-f1"], default="accuracy")
    parser.add_argument("--dropout", type=float, default=None, help="Override the model dropout (defaults to the model config value).")
    parser.add_argument("--no-positional-encoding", action="store_true", help="Disable sinusoidal positional encoding.")
    parser.add_argument(
        "--architecture",
        choices=[TORCH_MODEL_ARCHITECTURE_V1, TORCH_MODEL_ARCHITECTURE_V2],
        default=TORCH_MODEL_ARCHITECTURE_V1,
        help="Select the saved artifact architecture. v2 can expose attention weights for diagnostics.",
    )
    parser.add_argument("--model-version", default="local-transformer-v1")
    parser.add_argument("--experiment-name")
    parser.add_argument("--experiments-dir", type=Path, default=Path("models/experiments"))
    parser.add_argument("--cpu", action="store_true")
    parser.add_argument(
        "--allow-unready-dataset",
        action="store_true",
        help="Bypass label-coverage guards for small test fixtures; not recommended for research runs.",
    )
    args = parser.parse_args()
    validate_split_ratios(args.validation_ratio, args.test_ratio)
    if args.batch_size <= 0:
        raise SystemExit("--batch-size must be greater than 0")
    if args.patience <= 0:
        raise SystemExit("--patience must be greater than 0")
    return args


def validate_validation_ratio(validation_ratio: float) -> None:
    if validation_ratio <= 0 or validation_ratio >= 1:
        raise SystemExit("--validation-ratio must be greater than 0 and less than 1")


def validate_split_ratios(validation_ratio: float, test_ratio: float) -> None:
    validate_validation_ratio(validation_ratio)
    if test_ratio <= 0 or test_ratio >= 1:
        raise SystemExit("--test-ratio must be greater than 0 and less than 1")
    if validation_ratio + test_ratio >= 1:
        raise SystemExit("--validation-ratio and --test-ratio must sum to less than 1")


def split_training_windows(items: list, validation_ratio: float) -> tuple[list, list]:
    # Keep training before validation in time; random splits would leak future regimes backward.
    split_index = chronological_split_index(len(items), validation_ratio)
    return items[:split_index], items[split_index:]


def label_distribution(labels: list[int], label_names: list[str]) -> dict[str, int]:
    return {
        label_name: labels.count(index)
        for index, label_name in enumerate(label_names)
    }


def load_torch():
    try:
        import torch
    except ModuleNotFoundError as exc:
        raise SystemExit("install requirements-torch.txt before training") from exc
    return torch


def load_candles(csv_path: Path) -> list[MarketRegimeCandle]:
    return load_market_regime_candles(csv_path)


def build_training_windows(
    candles: list[MarketRegimeCandle],
    sequence_length: int,
) -> tuple[list[list[list[float]]], list[int]]:
    return build_labeled_windows(candles, sequence_length)


def normalization_stats(windows: list[list[list[float]]]) -> tuple[list[float], list[float]]:
    feature_count = len(TORCH_MARKET_REGIME_FEATURE_ORDER)
    flattened = [row for window in windows for row in window]
    means = [
        sum(row[index] for row in flattened) / len(flattened)
        for index in range(feature_count)
    ]
    variances = [
        sum((row[index] - means[index]) ** 2 for row in flattened) / len(flattened)
        for index in range(feature_count)
    ]
    # Constant features get std 1.0 so normalization stays finite without changing that feature.
    stds = [variance ** 0.5 if variance > 0 else 1.0 for variance in variances]
    return means, stds


def normalize_window(
    window: list[list[float]],
    means: list[float],
    stds: list[float],
) -> list[list[float]]:
    return [[(value - means[index]) / stds[index] for index, value in enumerate(row)] for row in window]


def predict_validation_labels(torch, model, validation_windows: list[list[list[float]]], device) -> list[dict[str, float | int]]:
    predictions: list[dict[str, float | int]] = []
    with torch.no_grad():
        for window in validation_windows:
            input_tensor = torch.tensor([window], dtype=torch.float32, device=device)
            probabilities = torch.softmax(model(input_tensor), dim=-1)[0]
            confidence, label_index = probabilities.max(dim=0)
            predictions.append(
                {
                    "labelIndex": int(label_index.item()),
                    "confidence": round(float(confidence.item()) * 100, 4),
                }
            )
    return predictions


def validation_accuracy(predictions: list[dict[str, float | int]], expected_labels: list[int]) -> float:
    if not expected_labels:
        return 0
    correct = sum(
        1
        for prediction, expected_label in zip(predictions, expected_labels, strict=True)
        if prediction["labelIndex"] == expected_label
    )
    return round(correct / len(expected_labels), 4)


def git_commit() -> str | None:
    """Best effort current commit hash, None when git is unavailable."""
    import subprocess

    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    commit = result.stdout.strip()
    return commit or None


def reproducibility_block(seed: int, torch_version: str | None) -> dict:
    import platform

    return {
        "seed": seed,
        "gitCommit": git_commit(),
        "torchVersion": torch_version,
        "python": platform.python_version(),
    }


def write_experiment_manifest(
    args: argparse.Namespace,
    candles: list[MarketRegimeCandle],
    windows: list[list[list[float]]],
    train_windows: list[list[list[float]]],
    validation_windows: list[list[list[float]]],
    train_labels: list[int],
    validation_labels: list[int],
    test_labels: list[int],
    test_window_count: int,
    model_config: dict,
    training_outcome: dict,
    reproducibility: dict,
    device: str,
) -> tuple[Path, dict]:
    # The manifest is the audit trail for a local artifact: data hash, config, metrics, and environment.
    manifest = build_experiment_manifest(
        csv_path=args.csv_path,
        output_path=args.output,
        sequence_length=args.sequence_length,
        feature_order=TORCH_MARKET_REGIME_FEATURE_ORDER,
        labels=LABELS,
        split={
            "method": "chronological_train_validation_test",
            "validationRatio": args.validation_ratio,
            "testRatio": args.test_ratio,
        },
        training={
            "epochs": args.epochs,
            "learningRate": args.learning_rate,
            "batchSize": args.batch_size,
            "patience": args.patience,
            "modelVersion": args.model_version,
            "architecture": args.architecture,
            "model": model_config,
            "classWeighting": args.class_weighting,
            "classWeights": class_weights_for_manifest(args, train_labels),
            "selectionMetric": args.selection_metric,
            "epochHistory": training_outcome["epochHistory"],
            "bestEpoch": training_outcome["bestEpoch"],
            "earlyStopped": training_outcome["earlyStopped"],
        },
        window_count=len(windows),
        train_window_count=len(train_windows),
        validation_window_count=len(validation_windows),
        test_window_count=test_window_count,
        validation_ratio=args.validation_ratio,
        test_ratio=args.test_ratio,
        train_label_distribution=label_distribution(train_labels, LABELS),
        validation_label_distribution=label_distribution(validation_labels, LABELS),
        test_label_distribution=label_distribution(test_labels, LABELS),
        final_train_loss=training_outcome["finalTrainLoss"],
        validation_accuracy=training_outcome["validationAccuracy"],
        validation_macro_f1=training_outcome["validationMacroF1"],
        window_ranges=window_time_ranges(
            candles,
            args.sequence_length,
            len(train_windows),
            len(validation_windows),
            test_window_count,
        ),
        reproducibility=reproducibility,
        device=device,
    )
    manifest_path = args.output.with_suffix(args.output.suffix + ".manifest.json")
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest_path, manifest


def build_training_registry_entry(args: argparse.Namespace, manifest_path: Path, manifest: dict, run_id: str) -> dict:
    training = manifest.get("training", {})
    return {
        "name": args.experiment_name,
        "runId": run_id,
        "schemaVersion": manifest["schemaVersion"],
        "generatedAt": manifest["generatedAt"],
        "dataset": manifest["dataset"],
        "artifact": manifest["artifact"],
        "manifestPath": str(manifest_path),
        "modelVersion": args.model_version,
        "architecture": training.get("architecture"),
        "featureVersion": manifest["featureVersion"],
        "sequenceLength": args.sequence_length,
        "labels": manifest["labels"],
        "windowRanges": manifest["windowRanges"],
        "reproducibility": manifest.get("reproducibility"),
        "training": {
            "trainWindowCount": manifest["trainWindowCount"],
            "validationWindowCount": manifest["validationWindowCount"],
            "testWindowCount": manifest.get("testWindowCount"),
            "validationRatio": manifest["validationRatio"],
            "testRatio": manifest.get("testRatio"),
            "finalTrainLoss": manifest["finalTrainLoss"],
            "validationAccuracy": manifest["validationAccuracy"],
            "validationMacroF1": manifest.get("validationMacroF1"),
            "bestEpoch": training.get("bestEpoch"),
            "earlyStopped": training.get("earlyStopped"),
            "dropout": training.get("model", {}).get("dropout"),
            "usePositionalEncoding": training.get("model", {}).get("usePositionalEncoding"),
            "classWeighting": training.get("classWeighting"),
            "classWeights": training.get("classWeights"),
            "selectionMetric": training.get("selectionMetric"),
        },
    }


def window_time_ranges(
    candles: list[MarketRegimeCandle],
    sequence_length: int,
    train_window_count: int,
    validation_window_count: int,
    test_window_count: int = 0,
) -> dict[str, dict[str, str | None]]:
    window_end_times = [
        candle.openTime.isoformat()
        for candle in candles[sequence_length - 1 :]
    ]
    train_end_times = window_end_times[:train_window_count]
    validation_end_times = window_end_times[train_window_count : train_window_count + validation_window_count]
    test_start = train_window_count + validation_window_count
    test_end_times = window_end_times[test_start : test_start + test_window_count]
    return {
        "all": summarize_time_range(window_end_times),
        "train": summarize_time_range(train_end_times),
        "validation": summarize_time_range(validation_end_times),
        "test": summarize_time_range(test_end_times),
    }


def evaluation_holdout_metadata(
    args: argparse.Namespace,
    candles: list[MarketRegimeCandle],
    train_window_count: int,
    validation_window_count: int,
    test_window_count: int,
) -> dict:
    ranges = window_time_ranges(
        candles,
        args.sequence_length,
        train_window_count,
        validation_window_count,
        test_window_count,
    )
    return {
        "source": "artifact-test-split",
        "testRatio": args.test_ratio,
        "startWindowEnd": ranges["test"]["firstWindowEnd"],
        "endWindowEnd": ranges["test"]["lastWindowEnd"],
        "windowCount": test_window_count,
        "datasetSha256": describe_path(args.csv_path)["sha256"],
    }


def class_weights_for_manifest(args: argparse.Namespace, train_labels: list[int]) -> list[float] | None:
    return balanced_class_weights(train_labels, len(LABELS)) if args.class_weighting == "balanced" else None


def summarize_time_range(values: list[str]) -> dict[str, str | None]:
    if not values:
        return {"firstWindowEnd": None, "lastWindowEnd": None}
    return {"firstWindowEnd": values[0], "lastWindowEnd": values[-1]}


def register_training_experiment(args: argparse.Namespace, manifest_path: Path, manifest: dict, run_id: str) -> None:
    registry_path = args.experiments_dir / "index.json"
    registry = load_experiment_registry(registry_path)
    # Training and evaluation share a run id so later evaluation can merge into the same registry entry.
    registry = append_or_merge_run(registry, build_training_registry_entry(args, manifest_path, manifest, run_id))
    write_experiment_registry(registry_path, registry)


if __name__ == "__main__":
    main()
