import argparse
import csv
import json
import sys
from datetime import datetime
from decimal import Decimal
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from app.schemas.market_regime_schema import MarketRegimeCandle, MarketRegimeRequest
from app.services.market_regime_service import RuleBasedMarketRegimeClassifier
from app.services.market_regime_experiment import MARKET_REGIME_FEATURE_VERSION, build_experiment_manifest
from app.services.market_regime_experiment import (
    append_or_merge_run,
    chronological_split_index,
    generate_run_id,
    load_experiment_registry,
    write_experiment_registry,
)
from app.services.market_regime_torch_features import (
    TORCH_MARKET_REGIME_FEATURE_ORDER,
    build_torch_feature_matrix,
)
from app.services.market_regime_torch_model import DEFAULT_TORCH_MODEL_CONFIG, TORCH_MODEL_ARCHITECTURE_V1, build_transformer_model


LABELS = ["SIDEWAYS", "TRENDING_UP", "TRENDING_DOWN", "HIGH_VOLATILITY"]


def main() -> None:
    args = parse_args()
    torch = load_torch()
    seed_everything(torch, args.seed)
    run_id = generate_run_id()
    candles = load_candles(args.csv_path)
    windows, labels = build_training_windows(candles, args.sequence_length)
    if not windows:
        raise SystemExit("not enough candles to build training windows")
    # Labels are generated by the rules classifier, so the model learns a weak-label baseline rather
    # than independent trading truth. Evaluation should be read as consistency and lift, not oracle accuracy.
    train_windows, validation_windows = split_training_windows(windows, args.validation_ratio)
    train_labels, validation_labels = split_training_windows(labels, args.validation_ratio)

    # Fit normalization on training windows only, then reuse those stats for validation and inference.
    # This avoids leaking later validation-window statistics into training-time preprocessing.
    means, stds = normalization_stats(train_windows)
    normalized_train_windows = [
        normalize_window(window, means, stds)
        for window in train_windows
    ]
    normalized_validation_windows = [
        normalize_window(window, means, stds)
        for window in validation_windows
    ]
    device = torch.device("cuda" if torch.cuda.is_available() and not args.cpu else "cpu")
    model_config = build_model_config(args)

    inputs = torch.tensor(normalized_train_windows, dtype=torch.float32, device=device)
    targets = torch.tensor(train_labels, dtype=torch.long, device=device)
    model = build_transformer_model(
        torch,
        feature_count=len(TORCH_MARKET_REGIME_FEATURE_ORDER),
        class_count=len(LABELS),
        config=model_config,
    ).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.learning_rate)
    loss_function = torch.nn.CrossEntropyLoss()

    training_outcome = train_with_early_stopping(
        torch,
        model,
        optimizer,
        loss_function,
        inputs,
        targets,
        normalized_validation_windows,
        validation_labels,
        epochs=args.epochs,
        batch_size=args.batch_size,
        patience=args.patience,
        seed=args.seed,
        device=device,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "metadata": {
                "runId": run_id,
                "modelVersion": args.model_version,
                "featureVersion": MARKET_REGIME_FEATURE_VERSION,
                "sequenceLength": args.sequence_length,
                "featureOrder": TORCH_MARKET_REGIME_FEATURE_ORDER,
                "labels": LABELS,
                "architecture": TORCH_MODEL_ARCHITECTURE_V1,
                "normalization": {"mean": means, "std": stds},
                "model": model_config,
            },
            "modelStateDict": model.cpu().state_dict(),
        },
        args.output,
    )
    manifest_path, manifest = write_experiment_manifest(
        args,
        candles,
        windows,
        train_windows,
        validation_windows,
        train_labels,
        validation_labels,
        model_config,
        training_outcome,
        reproducibility_block(args.seed, getattr(torch, "__version__", None)),
        str(device),
    )
    if args.experiment_name:
        register_training_experiment(args, manifest_path, manifest, run_id)


def seed_everything(torch, seed: int) -> None:
    import random

    # Seed Python and torch so repeated local runs are comparable when config is unchanged.
    random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def build_model_config(args: argparse.Namespace) -> dict:
    config = dict(DEFAULT_TORCH_MODEL_CONFIG)
    if args.dropout is not None:
        config["dropout"] = args.dropout
    if args.no_positional_encoding:
        config["usePositionalEncoding"] = False
    return config


def build_minibatches(item_count: int, batch_size: int, seed: int) -> list[list[int]]:
    """Return a deterministic shuffled set of index batches for one epoch."""
    import random

    indices = list(range(item_count))
    random.Random(seed).shuffle(indices)
    return [indices[start : start + batch_size] for start in range(0, item_count, batch_size)]


def select_best_epoch(history: list[dict[str, float]]) -> int:
    """Return the 1 based epoch with the highest validation accuracy.

    Ties keep the earliest epoch so we favour the simpler, earlier model.
    """
    best_index = 0
    for index in range(1, len(history)):
        if history[index]["valAccuracy"] > history[best_index]["valAccuracy"]:
            best_index = index
    return best_index + 1


def train_with_early_stopping(
    torch,
    model,
    optimizer,
    loss_function,
    inputs,
    targets,
    normalized_validation_windows: list[list[list[float]]],
    validation_labels: list[int],
    *,
    epochs: int,
    batch_size: int,
    patience: int,
    seed: int,
    device,
) -> dict:
    item_count = int(inputs.shape[0])
    history: list[dict[str, float]] = []
    best_val_accuracy = -1.0
    best_state = None
    best_epoch = 0
    epochs_without_improvement = 0
    early_stopped = False

    for epoch in range(1, epochs + 1):
        model.train()
        batch_losses: list[float] = []
        for batch_indices in build_minibatches(item_count, batch_size, seed + epoch):
            # Change the shuffle seed per epoch while keeping the whole run reproducible.
            index_tensor = torch.tensor(batch_indices, dtype=torch.long, device=device)
            batch_inputs = inputs.index_select(0, index_tensor)
            batch_targets = targets.index_select(0, index_tensor)
            optimizer.zero_grad()
            loss = loss_function(model(batch_inputs), batch_targets)
            loss.backward()
            optimizer.step()
            batch_losses.append(float(loss.item()))

        train_loss = round(sum(batch_losses) / len(batch_losses), 6) if batch_losses else 0.0
        model.eval()
        predictions = predict_validation_labels(torch, model, normalized_validation_windows, device)
        val_accuracy = validation_accuracy(predictions, validation_labels)
        val_loss = validation_loss(torch, model, loss_function, normalized_validation_windows, validation_labels, device)
        history.append(
            {
                "epoch": epoch,
                "trainLoss": train_loss,
                "valLoss": val_loss,
                "valAccuracy": val_accuracy,
            }
        )

        if val_accuracy > best_val_accuracy:
            # Keep the best validation state, not just the final epoch.
            best_val_accuracy = val_accuracy
            best_state = {key: value.detach().clone() for key, value in model.state_dict().items()}
            best_epoch = epoch
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1
            if epochs_without_improvement >= patience:
                early_stopped = True
                break

    if best_state is not None:
        model.load_state_dict(best_state)

    best_record = history[best_epoch - 1] if history else {"trainLoss": 0.0, "valAccuracy": 0.0}
    return {
        "epochHistory": history,
        "bestEpoch": best_epoch,
        "earlyStopped": early_stopped,
        "finalTrainLoss": best_record["trainLoss"],
        "validationAccuracy": best_record["valAccuracy"],
    }


def validation_loss(
    torch,
    model,
    loss_function,
    normalized_validation_windows: list[list[list[float]]],
    validation_labels: list[int],
    device,
) -> float:
    if not normalized_validation_windows:
        return 0.0
    with torch.no_grad():
        inputs = torch.tensor(normalized_validation_windows, dtype=torch.float32, device=device)
        targets = torch.tensor(validation_labels, dtype=torch.long, device=device)
        return round(float(loss_function(model(inputs), targets).item()), 6)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train a local market-regime torch artifact.")
    parser.add_argument("--csv-path", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--sequence-length", type=int, default=20)
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--learning-rate", type=float, default=0.001)
    parser.add_argument("--validation-ratio", type=float, default=0.2)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--patience", type=int, default=10, help="Stop after this many epochs without validation improvement.")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--dropout", type=float, default=None, help="Override the model dropout (defaults to the model config value).")
    parser.add_argument("--no-positional-encoding", action="store_true", help="Disable sinusoidal positional encoding.")
    parser.add_argument("--model-version", default="local-transformer-v1")
    parser.add_argument("--experiment-name")
    parser.add_argument("--experiments-dir", type=Path, default=Path("models/experiments"))
    parser.add_argument("--cpu", action="store_true")
    args = parser.parse_args()
    validate_validation_ratio(args.validation_ratio)
    if args.batch_size <= 0:
        raise SystemExit("--batch-size must be greater than 0")
    if args.patience <= 0:
        raise SystemExit("--patience must be greater than 0")
    return args


def validate_validation_ratio(validation_ratio: float) -> None:
    if validation_ratio <= 0 or validation_ratio >= 1:
        raise SystemExit("--validation-ratio must be greater than 0 and less than 1")


def split_training_windows(items: list, validation_ratio: float) -> tuple[list, list]:
    # Keep training before validation in time; random splits would leak future regimes backward.
    split_index = chronological_split_index(len(items), validation_ratio)
    return items[:split_index], items[split_index:]


def label_distribution(labels: list[int], label_names: list[str]) -> dict[str, int]:
    return {
        label_name: labels.count(index)
        for index, label_name in enumerate(label_names)
    }


def load_torch():
    try:
        import torch
    except ModuleNotFoundError as exc:
        raise SystemExit("install requirements-torch.txt before training") from exc
    return torch


def load_candles(csv_path: Path) -> list[MarketRegimeCandle]:
    with csv_path.open(newline="") as file:
        rows = csv.DictReader(file)
        return [
            MarketRegimeCandle(
                openTime=parse_datetime(row["openTime"]),
                open=Decimal(row["open"]),
                high=Decimal(row["high"]),
                low=Decimal(row["low"]),
                close=Decimal(row["close"]),
                volume=Decimal(row["volume"]),
            )
            for row in rows
        ]


def parse_datetime(value: str) -> datetime:
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def build_training_windows(
    candles: list[MarketRegimeCandle],
    sequence_length: int,
) -> tuple[list[list[list[float]]], list[int]]:
    classifier = RuleBasedMarketRegimeClassifier()
    windows: list[list[list[float]]] = []
    labels: list[int] = []

    for end_index in range(sequence_length, len(candles) + 1):
        window = candles[end_index - sequence_length : end_index]
        request = MarketRegimeRequest(symbol="local", timeframe="local", candles=window)
        # Labels come from the rule classifier, so this is distillation rather than market truth.
        label = classifier.classify(request).regimeLabel
        windows.append(build_torch_feature_matrix(window))
        labels.append(LABELS.index(label))

    return windows, labels


def normalization_stats(windows: list[list[list[float]]]) -> tuple[list[float], list[float]]:
    feature_count = len(TORCH_MARKET_REGIME_FEATURE_ORDER)
    flattened = [row for window in windows for row in window]
    means = [
        sum(row[index] for row in flattened) / len(flattened)
        for index in range(feature_count)
    ]
    variances = [
        sum((row[index] - means[index]) ** 2 for row in flattened) / len(flattened)
        for index in range(feature_count)
    ]
    # Constant features get std 1.0 so normalization stays finite without changing that feature.
    stds = [variance ** 0.5 if variance > 0 else 1.0 for variance in variances]
    return means, stds


def normalize_window(
    window: list[list[float]],
    means: list[float],
    stds: list[float],
) -> list[list[float]]:
    return [[(value - means[index]) / stds[index] for index, value in enumerate(row)] for row in window]


def predict_validation_labels(torch, model, validation_windows: list[list[list[float]]], device) -> list[dict[str, float | int]]:
    predictions: list[dict[str, float | int]] = []
    with torch.no_grad():
        for window in validation_windows:
            input_tensor = torch.tensor([window], dtype=torch.float32, device=device)
            probabilities = torch.softmax(model(input_tensor), dim=-1)[0]
            confidence, label_index = probabilities.max(dim=0)
            predictions.append(
                {
                    "labelIndex": int(label_index.item()),
                    "confidence": round(float(confidence.item()) * 100, 4),
                }
            )
    return predictions


def validation_accuracy(predictions: list[dict[str, float | int]], expected_labels: list[int]) -> float:
    if not expected_labels:
        return 0
    correct = sum(
        1
        for prediction, expected_label in zip(predictions, expected_labels, strict=True)
        if prediction["labelIndex"] == expected_label
    )
    return round(correct / len(expected_labels), 4)


def git_commit() -> str | None:
    """Best effort current commit hash, None when git is unavailable."""
    import subprocess

    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    commit = result.stdout.strip()
    return commit or None


def reproducibility_block(seed: int, torch_version: str | None) -> dict:
    import platform

    return {
        "seed": seed,
        "gitCommit": git_commit(),
        "torchVersion": torch_version,
        "python": platform.python_version(),
    }


def write_experiment_manifest(
    args: argparse.Namespace,
    candles: list[MarketRegimeCandle],
    windows: list[list[list[float]]],
    train_windows: list[list[list[float]]],
    validation_windows: list[list[list[float]]],
    train_labels: list[int],
    validation_labels: list[int],
    model_config: dict,
    training_outcome: dict,
    reproducibility: dict,
    device: str,
) -> tuple[Path, dict]:
    # The manifest is the audit trail for a local artifact: data hash, config, metrics, and environment.
    manifest = build_experiment_manifest(
        csv_path=args.csv_path,
        output_path=args.output,
        sequence_length=args.sequence_length,
        feature_order=TORCH_MARKET_REGIME_FEATURE_ORDER,
        labels=LABELS,
        split={
            "method": "chronological_holdout",
            "validationRatio": args.validation_ratio,
        },
        training={
            "epochs": args.epochs,
            "learningRate": args.learning_rate,
            "batchSize": args.batch_size,
            "patience": args.patience,
            "modelVersion": args.model_version,
            "model": model_config,
            "epochHistory": training_outcome["epochHistory"],
            "bestEpoch": training_outcome["bestEpoch"],
            "earlyStopped": training_outcome["earlyStopped"],
        },
        window_count=len(windows),
        train_window_count=len(train_windows),
        validation_window_count=len(validation_windows),
        validation_ratio=args.validation_ratio,
        train_label_distribution=label_distribution(train_labels, LABELS),
        validation_label_distribution=label_distribution(validation_labels, LABELS),
        final_train_loss=training_outcome["finalTrainLoss"],
        validation_accuracy=training_outcome["validationAccuracy"],
        window_ranges=window_time_ranges(
            candles,
            args.sequence_length,
            len(train_windows),
            len(validation_windows),
        ),
        reproducibility=reproducibility,
        device=device,
    )
    manifest_path = args.output.with_suffix(args.output.suffix + ".manifest.json")
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest_path, manifest


def build_training_registry_entry(args: argparse.Namespace, manifest_path: Path, manifest: dict, run_id: str) -> dict:
    training = manifest.get("training", {})
    return {
        "name": args.experiment_name,
        "runId": run_id,
        "schemaVersion": manifest["schemaVersion"],
        "generatedAt": manifest["generatedAt"],
        "dataset": manifest["dataset"],
        "artifact": manifest["artifact"],
        "manifestPath": str(manifest_path),
        "modelVersion": args.model_version,
        "featureVersion": manifest["featureVersion"],
        "sequenceLength": args.sequence_length,
        "labels": manifest["labels"],
        "windowRanges": manifest["windowRanges"],
        "reproducibility": manifest.get("reproducibility"),
        "training": {
            "trainWindowCount": manifest["trainWindowCount"],
            "validationWindowCount": manifest["validationWindowCount"],
            "validationRatio": manifest["validationRatio"],
            "finalTrainLoss": manifest["finalTrainLoss"],
            "validationAccuracy": manifest["validationAccuracy"],
            "bestEpoch": training.get("bestEpoch"),
            "earlyStopped": training.get("earlyStopped"),
            "dropout": training.get("model", {}).get("dropout"),
            "usePositionalEncoding": training.get("model", {}).get("usePositionalEncoding"),
        },
    }


def window_time_ranges(
    candles: list[MarketRegimeCandle],
    sequence_length: int,
    train_window_count: int,
    validation_window_count: int,
) -> dict[str, dict[str, str | None]]:
    window_end_times = [
        candle.openTime.isoformat()
        for candle in candles[sequence_length - 1 :]
    ]
    train_end_times = window_end_times[:train_window_count]
    validation_end_times = window_end_times[train_window_count : train_window_count + validation_window_count]
    return {
        "all": summarize_time_range(window_end_times),
        "train": summarize_time_range(train_end_times),
        "validation": summarize_time_range(validation_end_times),
    }


def summarize_time_range(values: list[str]) -> dict[str, str | None]:
    if not values:
        return {"firstWindowEnd": None, "lastWindowEnd": None}
    return {"firstWindowEnd": values[0], "lastWindowEnd": values[-1]}


def register_training_experiment(args: argparse.Namespace, manifest_path: Path, manifest: dict, run_id: str) -> None:
    registry_path = args.experiments_dir / "index.json"
    registry = load_experiment_registry(registry_path)
    # Training and evaluation share a run id so later evaluation can merge into the same registry entry.
    registry = append_or_merge_run(registry, build_training_registry_entry(args, manifest_path, manifest, run_id))
    write_experiment_registry(registry_path, registry)


if __name__ == "__main__":
    main()
