package com.signalattention.risk;

public enum RiskReasonCode {
    POLICY_FOUND,
    POSITION_SIZE_WITHIN_LIMIT,
    POSITION_SIZE_EXCEEDS_LIMIT,
    DAILY_LOSS_WITHIN_LIMIT,
    MAX_DAILY_LOSS_EXCEEDED,
    STOP_LOSS_TRIGGERED,
    TAKE_PROFIT_TRIGGERED,
    COOLDOWN_ACTIVE
}
